version: '3.8'

services: 
  app: 
    build: . 
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app    

  database:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=letscode
      - POSTGRES_USER=letscode
      - POSTGRES_DB=letscodedb

